[functions]
directory = "_api"

[[redirects]]
from = "/api/comments/*"
to = "/.netlify/functions/comments/:splat"
status = 200


[build]
edge_functions = "_api/_edge"

[[edge_functions]]
path = "/api/suggest"
function = "suggest"

[[edge_functions]]
path = "/api/search"
function = "search"


[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs]
output_path = "lighthouse.html"
